db:
  image: postgres
  ports:
    - "5432"

redis:
  image: redis
  ports:
    - "6379"

web:
  build: .
  command: bundle exec rails s -b 0.0.0.0
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
    - redis
