
if %w(development test).include? Rails.env
  require 'slim_lint/rake_task'
  SlimLint::RakeTask.new

  require 'rubocop/rake_task'
  RuboCop::RakeTask.new

  task(:default).clear
  task default: %i(spec rubocop slim_lint factory_girl:lint)
end
